services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: url-shortner
    container_name: url-shortner
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./backend/.env
    environment:
      - LOG_LEVEL=INFO
      - BASE_URL=http://localhost
    volumes:
      - ./backend/.logs:/app/backend/.logs
    restart: unless-stopped
