services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: url-shortner
    container_name: url-shortner
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./backend/.logs:/app/backend/.logs
    restart: unless-stopped
